apiVersion: apps/v1
kind: Deployment
metadata:
  name: job4j-devops
  labels:
    app: calculator # Label for the deployment(смотри в service.yaml, раздел selector:app: calculator)
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: lupusgrey/job4j_devops:v.1
          ports:
            - containerPort: 8080