# Deployment -This file describes the Deployment object in Kubernetes, which is responsible for managing and scaling pods.
apiVersion: apps/v1
kind: Deployment # Type of the Kubernetes object (Определяет тип Kubernetes-объекта, который мы хотим создать, в данном случае это Deployment.)
metadata:
  name: job4j-devops
  labels:
    app: calculator # Label for the deployment(смотри в service.yaml, раздел selector:app: calculator)
spec: # Specification of the deployment
  replicas: 3 # Number of replicas
  selector: # Selector for the deployment (which pods will be managed by this deployment)
    matchLabels:
      app: calculator # Label for the deployment -for Pod
  template: # sections Template: Section that describes the template that will be used to create pods.
    metadata:
      labels: # Labels for the pod
        app: calculator
    spec:
      containers: # List of containers which will be run in the pod
        - name: calculator # Name of the container
          image: lupusgrey/job4j_devops:v.1.0.1 # Docker image
          ports:
            - containerPort: 8080
          env:
            # Переменные из ConfigMap
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
               configMapKeyRef:
                 name: calculator
                 key: spring_profiles_active
            - name: SPRING_DATASOURCE_URL # Environment variable
              valueFrom: # Value of the environment variable - get this from ConfigMap file
                configMapKeyRef:
                  name: calculator
                  key: spring_datasource_url
            - name: SPRING_LIQUIBASE_URL
              valueFrom:
                configMapKeyRef:
                  name: calculator
                  key: spring_liquibase_url
            - name: SPRING_LIQUIBASE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: calculator
                  key: spring_liquibase_enabled

            # Секретные переменные из Secret \ secrets variables from Secret yaml
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: calculator # the name of the secret from secret.yaml
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: calculator
                  key: db_password
            - name: SPRING_LIQUIBASE_USER
              valueFrom:
                secretKeyRef:
                  name: calculator
                  key: spring_liquibase_user
            - name: SPRING_LIQUIBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: calculator
                  key: spring_liquibase_password
