apiVersion: v1
kind: Secret
metadata:
  name: calculator # name of the secret for using in deployment.yaml
type: Opaque # type of the secret, Opaque this means what we will use key-value pairs
data: # key-value pairs\it mey be used like springData or data \ - you may use it for using in deployment.yaml
  db_username: cG9zdGdyZXM=  # base64-кодированный "postgres"
  db_password: cGFzc3dvcmQ=  # base64-кодированный "password"
  spring_liquibase_user: cG9zdGdyZXM=  # base64-кодированный "postgres"
  spring_liquibase_password: cGFzc3dvcmQ=  # base64-кодированный "password"