apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  db_username: "postgres"
  db_password: "password"
  spring_liquibase_user: "postgres"
  spring_liquibase_password: "password"