secret: # Secret manifest
  username: "cG9zdGdyZXM="   # base64-кодированное "postgres"
  password: "cGFzc3dvcmQ="   # base64-кодированное "password"
  liquibase_user: "cG9zdGdyZXM="   # base64-кодированное "postgres"
  liquibase_password: "cGFzc3dvcmQ="   # base64-кодированное "password"

config: # ConfigMap manifest
  profiles_active: "local"
  database_url: "jdbc:postgresql://192.168.0.109:5432/job4j_devops?currentSchema=public&characterEncoding=UTF-8"
  liquibase_url: "jdbc:postgresql://192.168.0.109:5432/job4j_devops?currentSchema=public&characterEncoding=UTF-8"
  liquibase_enable: "true"

containers: # Deployment manifest
  image: "lupusgrey/job4j_devops:v.1.0.1"
