apiVersion: v1
kind: Secret
metadata:
  name: calculator # name of the secret for using in deployment.yaml
type: Opaque # type of the secret, Opaque this means what we will use key-value pairs
data: # key-value pairs\it mey be used like springData or data \ - you may use it for using in deployment.yaml
  db_username: {{ .Values.secret.username | quote }}  # base64-кодированный "postgres"
  db_password: {{ .Values.secret.password | quote }}  # base64-кодированный "password"
  spring_liquibase_user: {{ .Values.secret.liquibase_user | quote }}  # base64-кодированный "postgres"
  spring_liquibase_password: {{ .Values.secret.liquibase_password | quote }}  # base64-кодированный "password"