# This file describes a Service object in Kubernetes that provides access to pods through a single network interface.
# Этот файл описывает объект Service в Kubernetes, который предоставляет доступ к Подам через единый сетевой интерфейс.
apiVersion: v1
kind: Service # Service Type
metadata:
  name: calculator-service # Service Name -имя сервиса, которое используется для его идентификации в Kubernetes. Это должно быть уникальным в рамках вашего кластера.
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec: # Specification of the service - спецификация, описывающая, как должен работать объект Service.
  type: NodePort # Type of service - тип сервиса - NodePort/LoadBalancer, Kubernetes открывает порт на всех узлах кластера, через который можно получить доступ к сервису извне.
  selector: # Selects the pods to expose - выбирает поды, которые будут доступны через этот сервис. В данном случае, это поды с меткой app: calculator.
    app: calculator
  ports:
    - port: 8080 # Port on which the service is exposed - порт, на котором сервис будет доступен извне.
